initial documenation
metagraph-dev/metagraph-mlir pull request #4
Opened 2021-03-29 02:07 UTC by seibert

2021-03-29 17:46 UTC, paul-tqh-nguyen commented on docs/index.rst
> +The metagraph-mlir compiler requires that the decorated algorithm function
This might just be my personal preference, but it might be a good idea to show the example code before going into what all the parameters mean since:
- It's somewhat difficult to retain all the explanations while reading the code
- If we see the code first, it's expected that we not understand it. If we read the explanation later, we'll know that earlier there's an example we can refer to. 

It might look something like this:

- The metagraph-mlir compiler requires that the decorated algorithm function return a `MLIRFunc` object. Let's first look at an example.
- Suppose an abstract algorithm has already been defined to add two vectors: [INSERT CODE HERE]
- A concrete implementation of this algorithm in MLIR be written this way: [INSERT CODE HERE]
- The returned `MLIRFunc` instance from the function `compiled_add` contains a number of special attributes describing the algorithm, including: [INSERT THE REST HERE]

2021-03-29 17:49 UTC, paul-tqh-nguyen commented on docs/index.rst
> +The metagraph-mlir compiler requires that the decorated algorithm function
It' was not clear what "the decorated algorithm function" refers to on my first reading. Perhaps linking to https://metagraph.readthedocs.io/en/latest/user_guide/algorithms.html might be a good idea. 

Maybe something like this would work: "The metagraph-mlir compiler requires that the decorated algorithm function (see [here](https://metagraph.readthedocs.io/en/latest/user_guide/algorithms.html) for more about how to note an abstract or concrete algorithm with decorators) return a `MLIRFunc` object"

2021-03-29 17:50 UTC, paul-tqh-nguyen requested changes

2021-03-29 17:50 UTC, paul-tqh-nguyen commented on docs/index.rst
> +The metagraph-mlir compiler requires that the decorated algorithm function
This might just be my personal preference, but it might be a good idea to show the example code before going into what all the parameters mean since:
- It's somewhat difficult to retain all the explanations while reading the code
- If we see the code first, it's expected that we not understand it. If we read the explanation later, we'll know that earlier there's an example we can refer to. 

The change look something like this:

- The metagraph-mlir compiler requires that the decorated algorithm function return a `MLIRFunc` object. Let's first look at an example.
- Suppose an abstract algorithm has already been defined to add two vectors: [INSERT CODE HERE]
- A concrete implementation of this algorithm in MLIR be written this way: [INSERT CODE HERE]
- The returned `MLIRFunc` instance from the function `compiled_add` contains a number of special attributes describing the algorithm, including: [INSERT THE REST HERE]

2021-03-29 17:50 UTC, paul-tqh-nguyen commented on docs/index.rst
> +The metagraph-mlir compiler requires that the decorated algorithm function
It was not clear what "the decorated algorithm function" refers to on my first reading. Perhaps linking to https://metagraph.readthedocs.io/en/latest/user_guide/algorithms.html might be a good idea. 

Maybe something like this would work: "The metagraph-mlir compiler requires that the decorated algorithm function (see [here](https://metagraph.readthedocs.io/en/latest/user_guide/algorithms.html) for more about how to note an abstract or concrete algorithm with decorators) return a `MLIRFunc` object"

2021-03-30 16:10 UTC, seibert commented on docs/index.rst
> +The metagraph-mlir compiler requires that the decorated algorithm function
fixed

2021-03-30 16:10 UTC, merged